# Generated by Django 5.2.1 on 2025-05-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kruskalapi', '0002_alter_lesson_content_alter_question_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_user',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='response',
            field=models.TextField(default='null'),
        ),
    ]
